services:
  app:
    image: ghcr.io/andmbg/isochrones-berlin:latest
    ports:
      - "8080:8080"
    volumes:
      - cache-data:/app/data
    environment:
      - DEBUG=false

volumes:
  cache-data:
